name: Nightly RAPIDS Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *" # 5am UTC / 1am EST

# the static `nightly` string is needed to differentiate
# this concurrency config from similar configs that exist
# in called workflows, which causes problems
concurrency:
  group: nightly-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get-run-info:
    uses: ./.github/workflows/get-run-info.yaml
    secrets: inherit
    with:
      branch: branch-23.02
      repos: >-
        rapidsai/cudf
        rapidsai/cuml
        rapidsai/raft
        rapidsai/rmm
  rmm-build:
    needs: get-run-info
    uses: rapidsai/rmm/.github/workflows/build.yaml@branch-23.02
    secrets: inherit
    with:
      branch: ${{ fromJSON(needs.get-run-info.outputs.obj).branch }}
      date: ${{ fromJSON(needs.get-run-info.outputs.obj).date }}
      sha: ${{ fromJSON(needs.get-run-info.outputs.obj).shas.rmm }}
  rmm-tests:
    needs: [get-run-info, rmm-build]
    uses: rapidsai/rmm/.github/workflows/test.yaml@branch-23.02
    secrets: inherit
    with:
      branch: ${{ fromJSON(needs.get-run-info.outputs.obj).branch }}
      date: ${{ fromJSON(needs.get-run-info.outputs.obj).date }}
      sha: ${{ fromJSON(needs.get-run-info.outputs.obj).shas.rmm }}
  cudf-build:
    needs: [get-run-info, rmm-build]
    uses: rapidsai/cudf/.github/workflows/build.yaml@branch-23.02
    secrets: inherit
    with:
      branch: ${{ fromJSON(needs.get-run-info.outputs.obj).branch }}
      date: ${{ fromJSON(needs.get-run-info.outputs.obj).date }}
      sha: ${{ fromJSON(needs.get-run-info.outputs.obj).shas.cudf }}
  cudf-tests:
    needs: [get-run-info, cudf-build]
    uses: rapidsai/cudf/.github/workflows/test.yaml@branch-23.02
    secrets: inherit
    with:
      branch: ${{ fromJSON(needs.get-run-info.outputs.obj).branch }}
      date: ${{ fromJSON(needs.get-run-info.outputs.obj).date }}
      sha: ${{ fromJSON(needs.get-run-info.outputs.obj).shas.cudf }}
  raft-build:
    needs: [get-run-info]
    uses: rapidsai/raft/.github/workflows/build.yaml@branch-23.02
    secrets: inherit
    with:
      branch: ${{ fromJSON(needs.get-run-info.outputs.obj).branch }}
      date: ${{ fromJSON(needs.get-run-info.outputs.obj).date }}
      sha: ${{ fromJSON(needs.get-run-info.outputs.obj).shas.raft }}
  raft-tests:
    needs: [get-run-info, raft-build]
    uses: rapidsai/raft/.github/workflows/test.yaml@branch-23.02
    secrets: inherit
    with:
      branch: ${{ fromJSON(needs.get-run-info.outputs.obj).branch }}
      date: ${{ fromJSON(needs.get-run-info.outputs.obj).date }}
      sha: ${{ fromJSON(needs.get-run-info.outputs.obj).shas.raft }}
  cuml-build:
    needs: [get-run-info, cudf-build]
    uses: rapidsai/cuml/.github/workflows/build.yaml@branch-23.02
    secrets: inherit
    with:
      branch: ${{ fromJSON(needs.get-run-info.outputs.obj).branch }}
      date: ${{ fromJSON(needs.get-run-info.outputs.obj).date }}
      sha: ${{ fromJSON(needs.get-run-info.outputs.obj).shas.cuml }}
  cuml-tests:
    needs: [get-run-info, cuml-build]
    uses: rapidsai/cuml/.github/workflows/test.yaml@branch-23.02
    secrets: inherit
    with:
      branch: ${{ fromJSON(needs.get-run-info.outputs.obj).branch }}
      date: ${{ fromJSON(needs.get-run-info.outputs.obj).date }}
      sha: ${{ fromJSON(needs.get-run-info.outputs.obj).shas.cuml }}
